twitter:
  consumer_key: "blyfg3lP7dnStwvbrHynLw"
  consumer_secret: "3kLPHNavswaLr6AKw02K7Q8gfaMZCnguPUmG0twqz5U"
facebook:
  app_id: "108206109247248"
  app_secret: "b01893d7e043d1bf47d77d73964ecd8d"
